<?xml version="1.0" encoding="utf-8"?><Database Name="SecureAtm" Class="AtmSecureDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=SecureAtm;Persist Security Info=True;User ID=sa" SettingsObjectName="FtpServerUI.Properties.Settings" SettingsPropertyName="SecureAtmConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CardNumber" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CustomerNumber" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Atm" Member="Atms">
    <Type Name="Atm">
      <Column Name="AtmId" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Busy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="LogId" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductNumber" Type="System.String" DbType="NVarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerNumber" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Transaction]" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionNumber" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductNumber" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Debit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerNumber" Type="System.String" DbType="NVarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pin" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>